2D Numpy in Python
Estimated time needed: 20 minutes

Objectives
After completing this lab you will be able to:

Operate comfortably with numpy
Perform complex operations with numpy

In [139]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [140]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [141]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [142]:
# Show the numpy array dimensions

A.ndim

2

In [143]:
# Show the numpy array shape

A.shape

(3, 3)

In [144]:
# Show the numpy array size

A.size

9

In [145]:
# Access the element on the second row and third column

A[1, 2]

23

In [146]:
# Access the element on the second row and third column

A[1][2]

23

In [147]:
# Access the element on the first row and first column

A[0][0]

11

In [148]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [149]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [150]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [151]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [152]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [153]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [154]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [155]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [156]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [157]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [158]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [159]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [160]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [161]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [162]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [163]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [168]:
# Consider the following list a, convert it to Numpy Array.

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr1 = [1, 2, 3, 4]
arr2 = [5, 6, 7, 8]
arr3 = [9, 10, 11, 12]

A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [170]:
# Calculate the numpy array size.
A.size

12

In [174]:
# Access the element on the first row and first and second columns.
A[0][0:2]

array([1, 2])

In [175]:
# Perform matrix multiplication with the numpy arrays A and B.

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
Z = np.dot(A,B)
Z

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])